matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libopencv-dev libgflags-dev libgoogle-glog-dev libboost-dev

  - DIR=$(mktemp -d) && cd ${DIR}
  - git clone https://github.com/protocolbuffers/protobuf.git && cd protobuf
  - git submodule update --init --recursive
  - ./autogen.sh && ./configure && make && make check && sudo make install && sudo ldconfig

script:
  - cd app/interactiveLive && ./build.sh
