matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode8
      env: COMPILER=clang++-3.7

before_install:
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
        sudo apt-get update -qq
        sudo apt-get install -y libopencv-dev libgflags-dev libgoogle-glog-dev libboost-dev
        mkdir -p ~/protobuf3 && cd ~/protobuf3
        git clone https://github.com/protocolbuffers/protobuf.git && cd protobuf
        git submodule update --init --recursive
        ./autogen.sh && ./configure && make && make check && sudo make install && sudo ldconfig
    else
        rvm install ruby-2.3.3
        rvm --default use 2.3.3
        brew install cmake glog gflags protobuf
    fi

script:
  - |
    cd apps/interactiveLive && ./build.sh
